# Generated by Django 3.0.7 on 2020-06-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500, verbose_name='Title of the mail')),
                ('body', models.TextField(verbose_name='message content')),
                ('mail_to', models.CharField(max_length=250, verbose_name='Recipient')),
                ('mail_from', models.CharField(max_length=250, verbose_name='Sender')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
