# Generated by Django 3.0.7 on 2020-06-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingdetails',
            name='mail_from',
            field=models.EmailField(max_length=254, verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='mailingdetails',
            name='mail_to',
            field=models.EmailField(max_length=254, verbose_name='Recipient'),
        ),
    ]
